=== dkarlinsky/azsmrc/shared/src/main/java/lbms/tools/flexyconf/flexyconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="FlexyConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Section"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Section">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Entry"/>
        <xs:element ref="Section"/>
        <xs:element ref="Group"/>
      </xs:choice>
      <xs:attribute name="index" use="required" type="xs:integer"/>
      <xs:attribute name="label" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Group">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Entry"/>
      </xs:sequence>
      <xs:attribute name="index" use="required" type="xs:integer"/>
      <xs:attribute name="label" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Option"/>
      </xs:sequence>
      <xs:attribute name="dependsOn" type="xs:string"/>
      <xs:attribute name="index" use="required" type="xs:integer"/>
      <xs:attribute name="key" use="required" type="xs:string"/>
      <xs:attribute name="label" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="flexyType"/>
      <xs:attribute name="validate" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Option">
    <xs:complexType>
      <xs:attribute name="index" use="required" type="xs:integer"/>
      <xs:attribute name="label" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="flexyType">
  	<xs:restriction base="xs:string">
		<xs:enumeration value="integer"/>
		<xs:enumeration value="long"/>
		<xs:enumeration value="float"/>
		<xs:enumeration value="double"/>
		<xs:enumeration value="boolean"/>
		<xs:enumeration value="string"/>
		<xs:enumeration value="label"/>
		<xs:enumeration value="url"/>
	</xs:restriction>
  </xs:simpleType>
</xs:schema>

=== dkarlinsky/azsmrc/azsmrc/lbms/azsmrc/remote/client/swtgui/flexyconf/AzSMRCPreferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<FlexyConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../../../../tools/flexyconf/flexyconf.xsd">
	<Section label="mainLabel" index="0">
		<Section label="connection" index="0">
			<Entry key="auto_connect" label="connection.autoconnect" type="boolean" index="0"/>
			<Entry key="client.fastmode" label="connection.fastmode" type="boolean" index="1"/>
			<Entry key="connection_interval_open" label="connection.connection_interval_open" type="integer" index="2" validate="3000..65535"/>
			<Entry key="connection_interval_closed" label="connection.connection_interval_closed" type="integer" index="3" validate="3000..65535"/>
		</Section>
		<Section label="mainWindow" index="1">
			<Entry key="language" label="mainWindow.language" type="string" index="0">
				<Option Value="en_EN" Label="English" index="0"/>
				<Option Value="de_DE" Label="Deutsch" index="1"/>
			</Entry>
		</Section>


	</Section>
</FlexyConfiguration>
